server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workclub?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:com/**/mapper/xml/*.xml

jwt:
  tokenHeader: Token #JWT存储的请求头
  secret: workclub-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)

#file:
#  upload:
#    url: D:/文档/workclub

aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com # oss对外服务的访问域名
    accessKeyId:
      LTAI5tKJpRZHXc32VHcNMtkd # 访问身份验证中用到用户标识
    accessKeySecret:
      gYLiAbCxnH5Y1wp2Mjqm0DivHN6vsV # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: workclub-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: workclub/ # 上传文件夹路径前缀
